version: 2

jobs:
  build:
    machine:
      image: ubuntu-2404:2024.05.1
    resource_class: arm.medium
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Build and push Docker Image to Dockerhub
          command: |
            docker build -t hablijack/home-backend:1.7.4 .
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push hablijack/home-backend:1.7.4

workflows:
  version: 2
  qualitygate_and_build:
    jobs:
      - build
